// vue-app/src/App.vue
<script>
import SiteFooter from "./components/siteFooter/siteFooter.vue";

export default {
  components: {
    SiteFooter,
  },
};
</script>

<template>
  <div class="container">
    <div>Name: vue-app</div>
    <div>Framework: vue3</div>
    <div>Language: JavaScript</div>
    <div>CSS: Empty CSS</div>
    <SiteFooter />
  </div>
</template>

// receiver-app/src/App.jsx
import React, { useEffect } from "react";
import ReactDOM from "react-dom";
import Header from "host/header";

import "./index.css";

const launchFooter = () => {
  import("vue/mountFooter").then((mountFooter) => {
    mountFooter.default("#footer");
  });
};

const App = () => {
  useEffect(() => {
    launchFooter();
  }, []);

  return (
    <>
      <Header />
      <div className="container">
        <div>Name: host-app</div>
        <div>Framework: react</div>
        <div>Language: JavaScript</div>
        <div>CSS: Empty CSS</div>
        {/* <button onClick={launchFooter}>Launch footer</button> */}
      </div>
      <div id="footer" />
    </>
  );
};
ReactDOM.render(<App />, document.getElementById("app"));
