// vue-app/src/App.vue
<script>
import SiteFooter from "./components/siteFooter/siteFooter.vue";

export default {
  components: {
    SiteFooter,
  },
};
</script>

<template>
  <div class="container">
    <div>Name: vue-app</div>
    <div>Framework: vue3</div>
    <div>Language: JavaScript</div>
    <div>CSS: Empty CSS</div>
    <SiteFooter />
  </div>
</template>

// host-app/src/App.jsx
import React from "react";
import ReactDOM from "react-dom";
import Header from "./components/header/header";

import "./index.css";

const App = () => (
  <>
    <Header />
    <div className="container">
      <div>Name: host-app</div>
      <div>Framework: react</div>
      <div>Language: JavaScript</div>
      <div>CSS: Empty CSS</div>
    </div>
  </>
);
ReactDOM.render(<App />, document.getElementById("app"));
